name: First Workflow
# when workflow trigger (event name)
# workflow_dispatch - manual run
on: workflow_dispatch
jobs:
  first-job:
    # define runner (environment)
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: |
          echo "First output"
          echo "Second output"
      - name: Print goodbye
        run: echo "Done - bye!"
      
